Repository kakao-tech-campus-2nd-step3/Team13_BE, pull requests merged in 2024-09, with the labels that each got.

#12 #5 공용 db 연결하기
  build.gradle
  gradlew
  src/main/resources/application.properties
  src/main/resources/application.yml
  src/main/resources/database.yml
  src/main/resources/logging.yml
Labels: 🎉 feature

#14 feat: baseEntity 삭제 함수 추가
  src/main/java/dbdr/domain/BaseEntity.java
Labels: ⚙️ refactor

#17 [관리자 페이지] 돌봄대상자, 요양보호사 도메인 CRUD
  src/main/java/dbdr/controller/CareworkerController.java
  src/main/java/dbdr/controller/RecipientController.java
  src/main/java/dbdr/domain/BaseEntity.java
  src/main/java/dbdr/domain/Careworker.java
  src/main/java/dbdr/domain/Recipient.java
  src/main/java/dbdr/domain/chart/BodyManagement.java
  src/main/java/dbdr/domain/chart/Chart.java
  src/main/java/dbdr/domain/chart/NursingManagement.java
  src/main/java/dbdr/domain/chart/RecoveryTraining.java
  src/main/java/dbdr/dto/request/CareworkerRequestDTO.java
  src/main/java/dbdr/dto/request/RecipientRequestDTO.java
  src/main/java/dbdr/dto/response/CareworkerResponseDTO.java
  src/main/java/dbdr/dto/response/RecipientResponseDTO.java
  src/main/java/dbdr/repository/CareworkerRepository.java
  src/main/java/dbdr/repository/RecipientRepository.java
  src/main/java/dbdr/service/CareworkerService.java
  src/main/java/dbdr/service/RecipientService.java
Labels: 🎉 feature

#15 [관리자 페이지] 보호자 도메인 CRUD
  src/main/java/dbdr/controller/AdminGuardiansController.java
  src/main/java/dbdr/controller/GuardiansController.java
  src/main/java/dbdr/domain/Guardians.java
  src/main/java/dbdr/domain/chart/Chart.java
  src/main/java/dbdr/dto/request/GuardiansRequest.java
  src/main/java/dbdr/dto/response/GuardiansResponse.java
  src/main/java/dbdr/repository/GuardiansRepository.java
  src/main/java/dbdr/service/GuardiansService.java
Labels: 🎉 feature

#28 Week3 강철 멘토님 코드 리뷰 반영하기
  src/main/java/dbdr/domain/careworker/controller/CareworkerController.java
  src/main/java/dbdr/domain/careworker/entity/Careworker.java
  src/main/java/dbdr/domain/careworker/repository/CareworkerRepository.java
  src/main/java/dbdr/domain/careworker/service/CareworkerService.java
  src/main/java/dbdr/domain/guardian/controller/GuardianAdminController.java
  src/main/java/dbdr/domain/guardian/controller/GuardianController.java
  src/main/java/dbdr/domain/guardian/entity/Guardian.java
  src/main/java/dbdr/domain/guardian/service/GuardianService.java
  src/main/java/dbdr/domain/recipient/controller/RecipientController.java
  src/main/java/dbdr/domain/recipient/repository/RecipientRepository.java
  src/main/java/dbdr/domain/recipient/service/RecipientService.java
  src/main/java/dbdr/exception/IdNotFoundException.java
  src/main/java/dbdr/exception/NotUniqueException.java
  src/main/resources/application.yml
Labels: ⚙️ refactor

#30 @RestControllerAdvice를 이용한 예외처리 및 logging 설정
  src/main/java/dbdr/domain/careworker/controller/CareworkerController.java
  src/main/java/dbdr/domain/careworker/service/CareworkerService.java
  src/main/java/dbdr/domain/guardian/dto/request/GuardianRequest.java
  src/main/java/dbdr/domain/guardian/dto/response/GuardianResponse.java
  src/main/java/dbdr/domain/guardian/service/GuardianService.java
  src/main/java/dbdr/domain/recipient/controller/RecipientController.java
  src/main/java/dbdr/domain/recipient/service/RecipientService.java
  src/main/java/dbdr/exception/ApplicationError.java
  src/main/java/dbdr/exception/ApplicationException.java
  src/main/java/dbdr/exception/BusinessError.java
  src/main/java/dbdr/exception/BusinessException.java
  src/main/java/dbdr/exception/GlobalExceptionHandler.java
  src/main/java/dbdr/exception/IdNotFoundException.java
  src/main/java/dbdr/exception/NotUniqueException.java
  src/main/resources/logging.yml
Labels: 🎉 feature, 🤩 P1
