Repository kakao-tech-campus-2nd-step3/Team13_BE, pull requests merged in 2024-11, with the labels that each got.

#61 [Feature] 리프레시 토큰 적용
  build.gradle
  src/main/java/dbdr/domain/careworker/controller/CareworkerController.java
  src/main/java/dbdr/domain/chart/controller/CareWorkerChartController.java
  src/main/java/dbdr/global/configuration/RedisConfig.java
  src/main/java/dbdr/global/exception/ApplicationError.java
  src/main/java/dbdr/global/util/api/JwtUtils.java
  src/main/java/dbdr/security/config/ExceptionHandlingFilter.java
  src/main/java/dbdr/security/config/JwtFilter.java
  src/main/java/dbdr/security/config/SecurityConfig.java
  src/main/java/dbdr/security/controller/LoginController.java
  src/main/java/dbdr/security/dto/TokenDTO.java
  src/main/java/dbdr/security/service/JwtProvider.java
  src/main/java/dbdr/security/service/LoginService.java
  src/main/java/dbdr/security/service/RedisService.java
  src/test/java/dbdr/global/RedisTest.java
Labels: 🎉 feature

#68 Refactor: recipient, careworker
  src/main/java/dbdr/domain/careworker/controller/CareworkerController.java
  src/main/java/dbdr/domain/careworker/dto/request/CareworkerRequestDTO.java
  src/main/java/dbdr/domain/careworker/dto/response/CareworkerResponseDTO.java
  src/main/java/dbdr/domain/careworker/entity/Careworker.java
  src/main/java/dbdr/domain/careworker/repository/CareworkerRepository.java
  src/main/java/dbdr/domain/careworker/service/CareworkerService.java
  src/main/java/dbdr/domain/institution/controller/InstitutionAdminController.java
  src/main/java/dbdr/domain/institution/service/InstitutionService.java
  src/main/java/dbdr/domain/recipient/controller/RecipientController.java
  src/main/java/dbdr/domain/recipient/dto/request/RecipientRequestDTO.java
  src/main/java/dbdr/domain/recipient/dto/response/RecipientResponseDTO.java
  src/main/java/dbdr/domain/recipient/entity/Recipient.java
  src/main/java/dbdr/domain/recipient/service/RecipientService.java
Labels: ⚙️ refactor

#69 refactor: guardian, institution
  src/main/java/dbdr/domain/guardian/controller/GuardianController.java
  src/main/java/dbdr/domain/guardian/entity/Guardian.java
  src/main/java/dbdr/domain/institution/controller/InstitutionAdminController.java
  src/main/java/dbdr/domain/institution/service/InstitutionService.java
Labels: ⚙️ refactor

#71 refactor: chart
  src/main/java/dbdr/domain/chart/controller/CareWorkerChartController.java
  src/main/java/dbdr/domain/chart/dto/ChartMapper.java
  src/main/java/dbdr/domain/chart/dto/request/BodyManagementRequest.java
  src/main/java/dbdr/domain/chart/dto/request/ChartDetailRequest.java
  src/main/java/dbdr/domain/chart/dto/request/CognitiveManagementRequest.java
  src/main/java/dbdr/domain/chart/dto/request/NursingManagementRequest.java
  src/main/java/dbdr/domain/chart/dto/request/RecoveryTrainingRequest.java
  src/main/java/dbdr/domain/chart/dto/response/BodyManagementResponse.java
  src/main/java/dbdr/domain/chart/dto/response/CognitiveManagementResponse.java
  src/main/java/dbdr/domain/chart/dto/response/NursingManagementResponse.java
  src/main/java/dbdr/domain/chart/dto/response/RecoveryTrainingResponse.java
  src/main/java/dbdr/domain/chart/entity/BodyManagement.java
  src/main/java/dbdr/domain/chart/entity/CognitiveManagement.java
  src/main/java/dbdr/domain/chart/entity/NursingManagement.java
  src/main/java/dbdr/domain/chart/entity/RecoveryTraining.java
  src/main/java/dbdr/domain/institution/controller/InstitutionAdminController.java
  src/main/java/dbdr/domain/institution/service/InstitutionService.java
  src/main/java/dbdr/domain/recipient/service/RecipientService.java
  src/test/java/dbdr/chart/ChartMapperTest.java
  src/test/resources/application.yml
Labels: ⚙️ refactor

#59 LLM을 활용하여 돌봄대상자별 차트 요약하기
  src/main/java/dbdr/domain/careworker/controller/CareworkerController.java
  src/main/java/dbdr/domain/careworker/dto/request/CareworkerRequestDTO.java
  src/main/java/dbdr/domain/careworker/repository/CareworkerRepository.java
  src/main/java/dbdr/domain/careworker/service/CareworkerService.java
  src/main/java/dbdr/domain/chart/repository/ChartRepository.java
  src/main/java/dbdr/domain/chart/service/ChartService.java
  src/main/java/dbdr/domain/institution/controller/InstitutionAdminController.java
  src/main/java/dbdr/domain/institution/service/InstitutionService.java
  src/main/java/dbdr/domain/recipient/controller/RecipientController.java
  src/main/java/dbdr/exception/ApplicationError.java
  src/main/java/dbdr/global/configuration/OpenAiSummarizationConfig.java
  src/main/java/dbdr/global/configuration/OpenApiConfiguration.java
  src/main/java/dbdr/openai/controller/SummaryController.java
  src/main/java/dbdr/openai/dto/etc/Choice.java
  src/main/java/dbdr/openai/dto/etc/CompletionTokensDetails.java
  src/main/java/dbdr/openai/dto/etc/Message.java
  src/main/java/dbdr/openai/dto/etc/Usage.java
  src/main/java/dbdr/openai/dto/request/ChartDataRequest.java
  src/main/java/dbdr/openai/dto/request/OpenAiSummaryRequest.java
  src/main/java/dbdr/openai/dto/response/OpenAiSummaryResponse.java
  src/main/java/dbdr/openai/dto/response/SummaryResponse.java
  src/main/java/dbdr/openai/service/SummarizationService.java
  src/main/java/dbdr/security/config/JwtFilter.java
  src/main/java/dbdr/security/config/SecurityConfig.java
  src/main/java/dbdr/security/controller/LoginController.java
Labels: 🎉 feature

#78 summarization api refactor
  src/main/java/dbdr/domain/careworker/dto/request/CareworkerRequestDTO.java
  src/main/java/dbdr/domain/careworker/dto/response/CareworkerResponseDTO.java
  src/main/java/dbdr/domain/careworker/entity/Careworker.java
  src/main/java/dbdr/domain/chart/dto/request/ChartDetailRequest.java
  src/main/java/dbdr/domain/chart/repository/ChartRepository.java
  src/main/java/dbdr/domain/chart/service/ChartService.java
  src/main/java/dbdr/domain/recipient/dto/request/RecipientRequestDTO.java
  src/main/java/dbdr/domain/recipient/dto/response/RecipientResponseDTO.java
  src/main/java/dbdr/openai/controller/SummaryController.java
  src/main/java/dbdr/openai/dto/request/ChartDataRequest.java
  src/main/java/dbdr/openai/dto/response/SummaryAndTagResponse.java
  src/main/java/dbdr/openai/dto/response/SummaryResponse.java
  src/main/java/dbdr/openai/dto/response/TagResponse.java
  src/main/java/dbdr/openai/entity/Summary.java
  src/main/java/dbdr/openai/repository/SummaryRepository.java
  src/main/java/dbdr/openai/service/SummarizationService.java
  src/main/java/dbdr/openai/service/SummaryService.java
  src/test/resources/application.yml
Labels: ⚙️ refactor

#86 [차트 입력 기능] OCR + S3 + presigned url로 구현하기
  build.gradle
  src/main/java/dbdr/domain/careworker/WorkDay.java
  src/main/java/dbdr/domain/careworker/controller/CareworkerController.java
  src/main/java/dbdr/domain/careworker/controller/CareworkerInstitutionController.java
  src/main/java/dbdr/domain/careworker/dto/request/CareworkerUpdateRequest.java
  src/main/java/dbdr/domain/careworker/dto/response/CareworkerMyPageResponse.java
  src/main/java/dbdr/domain/careworker/entity/Careworker.java
  src/main/java/dbdr/domain/careworker/service/CareworkerMessagingService.java
  src/main/java/dbdr/domain/careworker/service/CareworkerService.java
  src/main/java/dbdr/domain/chart/controller/CareWorkerChartController.java
  src/main/java/dbdr/domain/core/alarm/entity/Alarm.java
  src/main/java/dbdr/domain/core/alarm/repository/AlarmRepository.java
  src/main/java/dbdr/domain/core/alarm/service/AlarmService.java
  src/main/java/dbdr/domain/core/messaging/MessageChannel.java
  src/main/java/dbdr/domain/core/messaging/MessageTemplate.java
  src/main/java/dbdr/domain/core/messaging/Role.java
  src/main/java/dbdr/domain/core/messaging/controller/LineController.java
  src/main/java/dbdr/domain/core/messaging/controller/SmsController.java
  src/main/java/dbdr/domain/core/messaging/dto/SqsMessageDto.java
  src/main/java/dbdr/domain/core/messaging/service/CallSqsService.java
  src/main/java/dbdr/domain/core/messaging/service/LineMessagingService.java
  src/main/java/dbdr/domain/core/messaging/service/LineService.java
  src/main/java/dbdr/domain/core/messaging/service/MessagingService.java
  src/main/java/dbdr/domain/core/messaging/service/SmsMessagingService.java
  src/main/java/dbdr/domain/core/messaging/service/SmsService.java
  src/main/java/dbdr/domain/core/messaging/util/MessagingScheduler.java
  src/main/java/dbdr/domain/core/ocr/controller/OcrController.java
  src/main/java/dbdr/domain/core/ocr/entity/OcrData.java
  src/main/java/dbdr/domain/core/ocr/repository/OcrRepository.java
  src/main/java/dbdr/domain/core/ocr/service/OcrService.java
  src/main/java/dbdr/domain/core/s3/controller/S3Controller.java
  src/main/java/dbdr/domain/core/s3/service/S3Service.java
  src/main/java/dbdr/domain/excel/controller/ExcelController.java
  src/main/java/dbdr/domain/guardian/controller/GuardianController.java
  src/main/java/dbdr/domain/guardian/controller/GuardianInstitutionController.java
  src/main/java/dbdr/domain/guardian/entity/Guardian.java
  src/main/java/dbdr/domain/guardian/service/GuardianMessagingService.java
  src/main/java/dbdr/domain/guardian/service/GuardianService.java
  src/main/java/dbdr/domain/recipient/controller/RecipientCareworkerController.java
  src/main/java/dbdr/domain/recipient/controller/RecipientInstitutionController.java
  src/main/java/dbdr/global/configuration/OpenApiConfiguration.java
  src/main/java/dbdr/global/configuration/S3Config.java
  src/main/java/dbdr/global/configuration/SqsConfig.java
  src/main/java/dbdr/global/util/line/LineMessagingScheduler.java
  src/main/java/dbdr/global/util/line/LineMessagingUtil.java
  src/main/java/dbdr/openai/controller/SummaryController.java
  src/main/java/dbdr/security/config/SecurityConfig.java
Labels: 🎉 feature, 🤩 P1

#87 [요양보호사/보호자] coolSMS API를 사용하여 SMS 알림 기능 구현하기
  build.gradle
  src/main/java/dbdr/domain/careworker/entity/Careworker.java
  src/main/java/dbdr/domain/careworker/service/CareworkerService.java
  src/main/java/dbdr/domain/chart/service/ChartService.java
  src/main/java/dbdr/domain/core/alarm/service/AlarmService.java
  src/main/java/dbdr/domain/core/messaging/MessageTemplate.java
  src/main/java/dbdr/domain/core/messaging/util/MessagingScheduler.java
  src/main/java/dbdr/domain/guardian/controller/GuardianController.java
  src/main/java/dbdr/domain/guardian/dto/request/GuardianAlertTimeRequest.java
  src/main/java/dbdr/domain/guardian/entity/Guardian.java
  src/main/java/dbdr/domain/guardian/service/GuardianService.java
  src/main/java/dbdr/global/configuration/WebConfig.java
  src/main/java/dbdr/security/config/SecurityConfig.java
Labels: 🎉 feature, 🤩 P1

#146 서비스 테스트 코드 작성하기 & 리드미 파일 최종 수정
  .github/workflows/gradle.yml
  README.md
  docs/source/be_structure.png
  docs/source/care_bridge.png
  docs/source/care_message.jpg
  docs/source/caregiver_difficulty.png
  docs/source/chart_summary.png
  docs/source/chart_view.png
  docs/source/chart_write.png
  docs/source/erd.png
  docs/source/ocr_example.png
  docs/source/voice_recognition.png
  src/main/java/dbdr/domain/core/messaging/util/MessagingScheduler.java
  src/main/java/dbdr/exception/ApplicationError.java
  src/test/java/dbdr/chart/OcrMockTest.java
  src/test/java/dbdr/messaging/AlarmServiceTest.java
  src/test/java/dbdr/messaging/CallSqsServiceTest.java
  src/test/java/dbdr/messaging/MessagingSchedulerTest.java
Labels: 🎉 feature, 📃 docs, 🤩 P1

#148 CI CD 해결
  .github/workflows/gradle.yml
  src/main/java/dbdr/domain/core/messaging/service/MessagingService.java
  src/main/java/dbdr/domain/guardian/dto/request/GuardianAlertTimeRequest.java
  src/main/java/dbdr/exception/ApplicationError.java
  src/main/java/dbdr/security/info.md
  src/test/java/dbdr/testhelper/readme.md
Labels: 🐞 bug
