Repository kakao-tech-campus-2nd-step3/Team13_BE, pull requests merged in 2024-10, with the labels that each got.

#39 [관리자 페이지] 요양원 도메인 CRUD
  src/main/java/dbdr/domain/guardian/controller/GuardianInstitutionController.java
  src/main/java/dbdr/domain/institution/controller/InstitutionAdminController.java
  src/main/java/dbdr/domain/institution/dto/request/InstitutionRequest.java
  src/main/java/dbdr/domain/institution/dto/response/InstitutionResponse.java
  src/main/java/dbdr/domain/institution/entity/Institution.java
  src/main/java/dbdr/domain/institution/repository/InstitutionRepository.java
  src/main/java/dbdr/domain/institution/service/InstitutionService.java
  src/main/java/dbdr/exception/ApplicationError.java
  src/main/resources/logging.yml
Labels: 🎉 feature

#33 차트 CRUD 구현, 공통 Response 포맷 작성
  build.gradle
  src/main/java/dbdr/DbdrApplication.java
  src/main/java/dbdr/domain/chart/BodyManagement.java
  src/main/java/dbdr/domain/chart/controller/CareWorkerChartController.java
  src/main/java/dbdr/domain/chart/controller/GuardianChartController.java
  src/main/java/dbdr/domain/chart/dto/ChartMapper.java
  src/main/java/dbdr/domain/chart/dto/request/BodyManagementRequest.java
  src/main/java/dbdr/domain/chart/dto/request/ChartDetailRequest.java
  src/main/java/dbdr/domain/chart/dto/request/CognitiveManagementRequest.java
  src/main/java/dbdr/domain/chart/dto/request/NursingManagementRequest.java
  src/main/java/dbdr/domain/chart/dto/request/RecoveryTrainingRequest.java
  src/main/java/dbdr/domain/chart/dto/response/BodyManagementResponse.java
  src/main/java/dbdr/domain/chart/dto/response/ChartDetailResponse.java
  src/main/java/dbdr/domain/chart/dto/response/CognitiveManagementResponse.java
  src/main/java/dbdr/domain/chart/dto/response/NursingManagementResponse.java
  src/main/java/dbdr/domain/chart/dto/response/RecoveryTrainingResponse.java
  src/main/java/dbdr/domain/chart/entity/BodyManagement.java
  src/main/java/dbdr/domain/chart/entity/Chart.java
  src/main/java/dbdr/domain/chart/entity/CognitiveManagement.java
  src/main/java/dbdr/domain/chart/entity/HealthBloodPressure.java
  src/main/java/dbdr/domain/chart/entity/NursingManagement.java
  src/main/java/dbdr/domain/chart/entity/PhysicalClear.java
  src/main/java/dbdr/domain/chart/entity/PhysicalMeal.java
  src/main/java/dbdr/domain/chart/entity/PhysicalWalk.java
  src/main/java/dbdr/domain/chart/entity/RecoveryTraining.java
  src/main/java/dbdr/domain/chart/repository/ChartRepository.java
  src/main/java/dbdr/domain/chart/service/ChartService.java
  src/main/java/dbdr/util/ApiUtils.java
  src/main/java/dbdr/util/Utils.java
  src/test/java/dbdr/chart/ChartMapperTest.java
Labels: 🎉 feature

#42 [요양보호사 / 보호자] Line messaging API를 활용하여 알림 서비스 구현하기
  build.gradle
  src/main/java/dbdr/DbdrApplication.java
  src/main/java/dbdr/domain/careworker/entity/Careworker.java
  src/main/java/dbdr/domain/careworker/repository/CareworkerRepository.java
  src/main/java/dbdr/domain/careworker/service/CareworkerMessagingService.java
  src/main/java/dbdr/domain/careworker/service/CareworkerService.java
  src/main/java/dbdr/domain/chart/controller/CareWorkerChartController.java
  src/main/java/dbdr/domain/chart/controller/GuardianChartController.java
  src/main/java/dbdr/domain/chart/dto/ChartMapper.java
  src/main/java/dbdr/domain/chart/dto/request/ChartDetailRequest.java
  src/main/java/dbdr/domain/chart/entity/BodyManagement.java
  src/main/java/dbdr/domain/chart/entity/Chart.java
  src/main/java/dbdr/domain/chart/entity/CognitiveManagement.java
  src/main/java/dbdr/domain/chart/entity/NursingManagement.java
  src/main/java/dbdr/domain/chart/entity/RecoveryTraining.java
  src/main/java/dbdr/domain/core/base/entity/BaseEntity.java
  src/main/java/dbdr/domain/core/messaging/controller/LineMessagingController.java
  src/main/java/dbdr/domain/core/messaging/service/LineMessagingService.java
  src/main/java/dbdr/domain/guardian/entity/Guardian.java
  src/main/java/dbdr/domain/guardian/repository/GuardianRepository.java
  src/main/java/dbdr/domain/guardian/service/GuardianMessagingService.java
  src/main/java/dbdr/domain/guardian/service/GuardianService.java
  src/main/java/dbdr/domain/institution/entity/Institution.java
  src/main/java/dbdr/domain/institution/service/InstitutionService.java
  src/main/java/dbdr/domain/recipient/entity/Recipient.java
  src/main/java/dbdr/domain/recipient/service/RecipientService.java
  src/main/java/dbdr/global/configuration/LineMessagingClientConfig.java
  src/main/java/dbdr/global/exception/ApplicationError.java
  src/main/java/dbdr/global/exception/ApplicationException.java
  src/main/java/dbdr/global/exception/BusinessError.java
  src/main/java/dbdr/global/exception/BusinessException.java
  src/main/java/dbdr/global/exception/GlobalExceptionHandler.java
  src/main/java/dbdr/global/util/api/ApiUtils.java
  src/main/java/dbdr/global/util/api/Utils.java
  src/main/java/dbdr/global/util/line/LineMessagingScheduler.java
  src/main/java/dbdr/global/util/line/LineMessagingUtil.java
  src/test/java/dbdr/chart/ChartMapperTest.java
Labels: 🎉 feature, 🤩 P1

#49 돌봄대상자/보호자/요양보호사 데이터 파일 입출력 기능 구현
  build.gradle
  src/main/java/dbdr/domain/careworker/entity/Careworker.java
  src/main/java/dbdr/domain/careworker/repository/CareworkerRepository.java
  src/main/java/dbdr/domain/excel/controller/ExcelController.java
  src/main/java/dbdr/domain/excel/dto/FileDataResponseDto.java
  src/main/java/dbdr/domain/excel/dto/FileUploadResponseDto.java
  src/main/java/dbdr/domain/excel/service/ExcelDownloadService.java
  src/main/java/dbdr/domain/excel/service/ExcelUploadService.java
  src/main/java/dbdr/domain/recipient/entity/Recipient.java
  src/main/java/dbdr/global/exception/ApplicationError.java
Labels: 🎉 feature, 🧐 P2

#56 chore : Repository 존재확인 메소드명 변경
  src/main/java/dbdr/domain/careworker/controller/CareworkerController.java
  src/main/java/dbdr/domain/careworker/repository/CareworkerRepository.java
  src/main/java/dbdr/domain/careworker/service/CareworkerService.java
  src/main/java/dbdr/domain/excel/service/ExcelUploadService.java
  src/main/java/dbdr/domain/guardian/repository/GuardianRepository.java
  src/main/java/dbdr/domain/guardian/service/GuardianService.java
  src/main/java/dbdr/domain/institution/repository/InstitutionRepository.java
  src/main/java/dbdr/domain/institution/service/InstitutionService.java
  src/main/java/dbdr/domain/recipient/repository/RecipientRepository.java
  src/main/java/dbdr/domain/recipient/service/RecipientService.java
  src/main/java/dbdr/security/service/BaseUserDetailsService.java
Labels: ⚙️ refactor
